language:
- python
sudo: false
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
env:
- INSTALLATION="python setup.py develop" XDIST=1
- INSTALLATION="pip install ." XDIST=0
before_install:
- mkdir /tmp/dynamodb
- wget -O - http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest
  | tar xz --directory /tmp/dynamodb
install:
- pip install -r requirements-test.txt
- "$INSTALLATION"
- pip install pytest_dbfixtures[mongodb,redis,rabbitmq,mysql,postgresql,dynamodb,tests]
  coveralls wheel
script:
- py.test -n $XDIST --cov pytest_dbfixtures tests
- pylama
after_success:
- coveralls
deploy:
  provider: pypi
  user: thearoom
  password:
    secure: W7fbSxVIuB6pHMLhzEwXG1GnxF+36hOC7RO2+Z1JoKFPFeRnz013GqZVgdvsjpu/Pb9t1dv+trjZqviIrauxKdGMqQxhtLl7A8G0j1sX59GG6DH/9iggAeJKWrcAt+czHXIPnpOopeNTqfTRs8cdaR7I+1wJzSS/tN6MUCanF6U=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ClearcodeHQ/pytest-dbfixtures
