language:
- python
sudo: false
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
env:
install:
- pip install -r requirements-test.txt wheel
script:
- pylama
deploy:
  provider: pypi
  user: thearoom
  password:
    secure: W7fbSxVIuB6pHMLhzEwXG1GnxF+36hOC7RO2+Z1JoKFPFeRnz013GqZVgdvsjpu/Pb9t1dv+trjZqviIrauxKdGMqQxhtLl7A8G0j1sX59GG6DH/9iggAeJKWrcAt+czHXIPnpOopeNTqfTRs8cdaR7I+1wJzSS/tN6MUCanF6U=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ClearcodeHQ/pytest-dbfixtures
