language:
- python
sudo: false
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
env:
  - INSTALLATION="python setup.py develop" XDIST=1
  # unfortunatelly, xdist hangs if there's any error in the slave threads, and there, pytest fires all the hooks
  - INSTALLATION="pip install ." XDIST=0
install:
- "pip install -r requirements-test.txt"
- $INSTALLATION
- pip install pytest_dbfixtures[mongodb,redis,rabbitmq,mysql,postgresql,elasticsearch,boto3,tests] coveralls wheel
- mkdir /tmp/dynamodb
- wget -O - http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest | tar xz --directory /tmp/dynamodb
script:
- py.test -n $XDIST --max-slave-restart=0 --showlocals --verbose --cov pytest_dbfixtures tests -p no:dbfixtures
- pylama
after_success:
- coveralls
deploy:
  provider: pypi
  user: thearoom
  password:
    secure: NA9uR63mHKFvh3Z5suAz3KKkWw8Mw/XF6QGsUJWPFOyPRiu4Ya4Kvc533XTXxqvImO/R17THuZ3TzzKz7OwbIPdz9kyQP/wpEuPAeYlGCZqEu2kzuKgPWFK/4udphB6k0irunf96KdQ1IExZao6ERKljpc8WSqA95BhZ2qHwduo=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ClearcodeHQ/pytest-dbfixtures
