language:
- python
sudo: false
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install:
- python setup.py develop
- pip install -e .[mongodb,redis,rabbitmq,mysql,postgresql,elasticsearch,tests]
- pip install wheel
script:
- py.test -n 1 --showlocals --verbose --cov pytest_dbfixtures tests -p no:dbfixtures
- pylama
after_success:
- coveralls
deploy:
  provider: pypi
  user: thearooom
  password:
    secure: "nxq7NY1SM4aX2SIj7Y1dNGcvY6HCn4/2SKeBrwYS+7XvyPvbhXgoYLY+2w1vrL9QXcjCNeFhJjyX3iI6yC/WfLM0nF/JskdD3npWpP+heul+IOECce0RRy1FqVa0cpcqrmYUuO6FsPFj76aSAJNT9edqjVPlISViRnTX955hebE="
  on:
    tags: true
    all_branches: true
    repo: ClearcodeHQ/pytest-dbfixtures
  distributions: sdist bdist_wheel
