language: python
python:
- '2.7'
before_script:
- wget -O - http://packages.elasticsearch.org/GPG-KEY-elasticsearch | sudo apt-key add -
- echo "deb http://packages.elasticsearch.org/elasticsearch/1.1/debian stable main" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install elasticsearch
install:
- python setup.py install
- pip install pymongo redis pika MySQL-python psycopg2 elasticsearch pylama
script:
- py.test -v tests
- pylama
deploy:
  provider: pypi
  user:
    secure: U82/Eiq193tV67k0QgXtJ8FGQvKTf9l4AuIis8jpAXrhWYGVH+GfASKFb9lGN8M/3tiXmCPZSP+WxEgSbBtcAIiDWiYkfVPnDf66AWf8glImyv/QOU+d8eSsP4dWrSpxo7mq+g94lhQ6cHSZtTCngU33VDCMu5RB+n27/AkS6co=
  password:
    secure: DRWW+buXoDjLjMDCiUKnnWiCVLUaei6iQsUTwU/3+UOPgd2htzAHo59X7GhF49N6cYG98qXZNayeM+a4QkHFnSCyzwFvlqrPpwnuINQtb0Bucoh9jnjKFq1OwAjaTdKz61YlRq6qaSXEGOKka08CN9Aj2UIUz/lNgMkZjkFmAIQ=
  on:
    tags: true
