language:
- python
sudo: false
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install:
- python setup.py develop
- pip install -e .[mongodb,redis,rabbitmq,mysql,postgresql,elasticsearch,tests]
- pip install wheel
script:
- py.test -n 1 --showlocals --verbose --cov pytest_dbfixtures tests -p no:dbfixtures
- pylama
after_success:
- coveralls
deploy:
  provider: pypi
  user: thearooom
  password:
    secure: A5I74CT7ZT6Ah8XUuAkKCgnCqPEdSnUJgQ+yb1v8D8kAS/FJA97e1fLt+iicVhgxzyYaP4nHtnq9t1evLEAHwnw6/L6KPAcSi5jDKTIuSPgSDTZfFtf9+GsLSaL1D3/9Og3u1zgo1tUwQBCz4HkwfeK1y0ZnezSMz6eFC1U2BvUAOO8hD/yxM/0svV2oSQIz3nMOZh877aG9RcCzDx+LvUE83v2WrrMnp9QFSjm7HvVl9BDglGHm/+rJ+0u+qLk9kXp17DN/VXDJn1DrueGyHgWtHfO5DCmSCD4akXgVvtiFRMRNgSBBkW636hu3jXZLw7L45c1WRxWRXxbrJr9qSLNLbOhkhr4Ms1YDtKoRfuJB7+vlesAc9/OpODuUNOcqyUhEQF0n3waKL8ocGIpiKogBvEtxgHmHqKjiyoNI/rlKsZKvLeWn/HHfzDlTngnhKQ7ryKMBy7WZrb3z2I9nRZ1Rw6P59ZYFl6z6rjfGmiQTcOR8tp/IrsAvlOhVDXd+FlgHG5WBoXLFFwVvTJRPJnwFbMr4tKvQIGnbRJp6YrxA9o1GDXXTc/rtsLKyr6AIMxQgajpubFTDbKcQfBRFJuxSmpJE0CI+MMDD/b0HaN2izkJ+2mO9m4MVV8LBMJeUS7WRr/t6Q7weQN1dDYXZtefQhyNsakWntq9cTx1FnLs=
  on:
    tags: true
    all_branches: true
    repo: ClearcodeHQ/pytest-dbfixtures
  distributions: sdist bdist_wheel
