language: python
python:
- '2.7'
- '3.3'
- '3.4'
before_install:
  - wget -O redis-2.4.14.tar.gz https://redis.googlecode.com/files/redis-2.4.14.tar.gz
  - tar xzf redis-2.4.14.tar.gz
  - cd redis-2.4.14
  - make
  - make test
  - sudo make install
  - cd utils
  - yes | sudo ./install_server.sh
  - cd ../../
  - /usr/local/bin/redis-server --version
  - /usr/bin/redis-server --version
install:
- "python setup.py develop"
- "pip install -e .[mongodb,redis,rabbitmq,mysql,postgresql,elasticsearch,tests]"
# manually install wheel for deployment
- "pip install wheel"
script:
- py.test -n 1 --showlocals --verbose --cov pytest_dbfixtures tests -p no:dbfixtures
- pylama
after_success:
    - coveralls

deploy:
  provider: pypi
  user:
    secure: U82/Eiq193tV67k0QgXtJ8FGQvKTf9l4AuIis8jpAXrhWYGVH+GfASKFb9lGN8M/3tiXmCPZSP+WxEgSbBtcAIiDWiYkfVPnDf66AWf8glImyv/QOU+d8eSsP4dWrSpxo7mq+g94lhQ6cHSZtTCngU33VDCMu5RB+n27/AkS6co=
  password:
    secure: DRWW+buXoDjLjMDCiUKnnWiCVLUaei6iQsUTwU/3+UOPgd2htzAHo59X7GhF49N6cYG98qXZNayeM+a4QkHFnSCyzwFvlqrPpwnuINQtb0Bucoh9jnjKFq1OwAjaTdKz61YlRq6qaSXEGOKka08CN9Aj2UIUz/lNgMkZjkFmAIQ=
  on:
    tags: true
    all_branches: true
    repo: ClearcodeHQ/pytest-dbfixtures
  distributions: "sdist bdist_wheel"
