language:
- python
sudo: false
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install:
- python setup.py develop
- pip install -e .[mongodb,redis,rabbitmq,mysql,postgresql,elasticsearch,tests]
- pip install wheel
script:
- py.test -n 1 --showlocals --verbose --cov pytest_dbfixtures tests -p no:dbfixtures
- pylama
after_success:
- coveralls
deploy:
  provider: pypi
  user: thearoom
  password:
    secure: NA9uR63mHKFvh3Z5suAz3KKkWw8Mw/XF6QGsUJWPFOyPRiu4Ya4Kvc533XTXxqvImO/R17THuZ3TzzKz7OwbIPdz9kyQP/wpEuPAeYlGCZqEu2kzuKgPWFK/4udphB6k0irunf96KdQ1IExZao6ERKljpc8WSqA95BhZ2qHwduo=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ClearcodeHQ/pytest-dbfixtures
